### ISSUE TITLE
How webmentions work ?

### ISSUE THREAD

**Issue by Phyks** [idno/idno#675]
Hi,

I'm not sure to fully understand the way webmentions work. I posted a quite long article on my Known instance, with a link in the post to [this article](http://werd.io/2014/being-a-human-on-the-internet-and-discovering-my-non-throttleable) from @benwerd .

The link was only here as an example, and it was not an answer or a comment on this article in any kind. But still, my post appear in the "comments" area on the other Known instance. Is it normal and expected ? I feel like my long post is "polluting" the comments with unrelated stuff.

Thanks

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/675" class="u-in-reply-to"></a>That is the normal behaviour for the webmention library, aye... however I agree that it's confusing behaviour. 

Not too sure what could be done better... most people linking to an article in a post (without explicitly *mentioning* in reply) would expect nothing more than a "hey, I mentioned you" ping, not a fully rendered comment.

Thoughts @benwerd?

**Comment by mapkyca** [comment]
Well, the expected behaviour in blogging software is that in text urls should be pinged, but that's the not the same as commenting. The problem is that the mentions library, and known, conflate two semantically different things here.

For known, I guess we can discover whether it's an in-text URL, and handle that differently (perhaps just a one line link (ala trad ping back) or a user notification or something. 

For web mentions in general, I'm not sure this has been entirely thought out... People seem to have originally intended webmention to supersede ping back, but in most cases they have two different intentions.

**Comment by mapkyca** [comment]
Perhaps there is a need for some new markup.... Perhaps in-text urls get a link-to or discussing-page class, and we handle those links differently when the mf2 parser finds them

**Comment by Phyks** [comment]
If I understand correctly, the new behaviour is the pingback mechanism discussed above. But we can't use a long post with on-reply-to to make them be a comment, true ?

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/idno/issues/675#issuecomment-69008390" class="u-in-reply-to"></a>See #671. It'd be handy to do long for replies, for a number of reasons, although the standard parsing of MF2 doesn't see a difference between titles and bodies.
