### ISSUE TITLE
Handle more complex mf2 combinations

### ISSUE THREAD

**Issue by benwerd** [idno/idno#701]
@kylewm used this post:

https://kylewm.com/2015/01/we-are-admiring-your-podcast-in-indiechat-i-hope

To link to this post:

http://werd.io/2014/shoplifters-and-thieves-podcastsunday

But Known didn't handle it because the microformats boiled down to a p-in-reply-to with a bunch of objects inside it. It's worth going back and making sure we support the full set of expected indieweb variables.

**Comment by kylewm** [comment]
tagging @Phyks too; he was helping me test this issue earlier.

**Comment by Phyks** [comment]
yep, same thing [here](https://kylewm.com/2015/01/interesting-this-is-basically-the-unofficial-api). While trying to debug it yesterday, I found some unassigned PHP variables, #699. After the fix for issue #699, I got an email notification when firing the webmention, but nothing shows in Known (no comment). Did not have time yesteday to debug it further, but you seem to have clues :)

**Comment by benwerd** [comment]
The notification should be triggered at the point at which it's saved, so this suggests a template issue. I'm checking it out.

**Comment by benwerd** [comment]
Mentions should now correctly display as of the latest commit (although new mentions will display a little better).

**Comment by benwerd** [comment]
I should clarify that this doesn't yet address properly determining mention _type_ when the contents of the reply URL class is a complex structure.

**Comment by Phyks** [comment]
@benwerd I updated to the latest commit. Same thing, notification triggered but nothing displayed in the template: https://known.phyks.me/2015/publishing-through-the-known-api.
